### ISSUE TITLE
Multiple matching signatures - bug?

### ISSUE THREAD

**Issue by oktonion** [anjo76/angelscript#14]
Hello,
so as promised I've created [AngelScript Standard Library](https://github.com/oktonion/astd). 
It works with version 2.37 well.

In the current versions of AngelScript library (v2.38.0 and v2.38.WIP) I've got an error in my [test script](https://github.com/oktonion/astd/blob/75227a56c9c9a061d356683df9dd4e78a2585ff7/tests/service/resources/script.as#L28).
```c++
string result = format("answer is '{:d}', test", 11, 12);
```

```
..\..\..\tests\chrono_tests.cpp(33): FATAL ERROR: "../../../tests/service/resources/script.as"" ("28", "25") : 
""Multiple matching signatures to 'format(const string, const int, const int)'"
```

I've registered function 'format' overloads in global and ```std``` namespaces as 
```c++
[0] "string format(const string&in format_str)"
[1] "string format(const string&in format_str, ?&in arg0)"
[2] "string format(const string&in format_str, ?&in arg0, ?&in arg1)"
[3] "string format(const string&in format_str, ?&in arg0, ?&in arg1, ?&in arg2)"
[4] "string format(const string&in format_str, ?&in arg0, ?&in arg1, ?&in arg2, ?&in arg3)"
[5] "string format(const string&in format_str, ?&in arg0, ?&in arg1, ?&in arg2, ?&in arg3, ?&in arg4)"
...
````

Why there is an error of "Multiple matching signatures" when there is clear matching overload [[2]](https://github.com/oktonion/astd/blob/75227a56c9c9a061d356683df9dd4e78a2585ff7/std/format/scriptstd_format.cpp#L187) ? Am I missing something or there were breaking changes since 2.37?

**Comment by anjo76** [comment]
I'll need to investigate this. You say you've registered the format functions in both global and std namespaces. Perhaps there is an issue with the lookup that matches both of them.

Doesn't the compiler report which of the multiple matching functions it is finding?

2.38.0 added the support for registering functions with variadic arguments. Though it's not a fix, you may want to use that instead of registering multiple different format functions.

**Comment by anjo76** [comment]
Ah yes. I thought about the format function in the add-on that was added in v2.38.0, but somehow I was thinking you were not using the add-ons that comes with the library and didn't mention it.

Still, the compiler should have informed the matching functions so you would have known immediately. Are you perhaps supressing the "INFO" messages?

I'll fix the error with the error for the asALREADY_REGISTERED. This is definitely a bug,

I will think about adjusting the logic for matching overloads to consider ... as the last option. I don't consider that a bug though, it is just an enhancement.

**Comment by oktonion** [comment]
> Ah yes. I thought about the format function in the add-on that was added in v2.38.0, but somehow I was thinking you were not using the add-ons that comes with the library and didn't mention it.

My bad. I completely forgot to mention that _'tiny'_ detail.

> Still, the compiler should have informed the matching functions so you would have known immediately. Are you perhaps supressing the "INFO" messages?
> 
> I'll fix the error with the error for the asALREADY_REGISTERED. This is definitely a bug,
> 
> I will think about adjusting the logic for matching overloads to consider ... as the last option. I don't consider that a bug though, it is just an enhancement.

Thanks for your time. Actually when the error with ```asALREADY_REGISTERED``` would be fixed then maybe all other logic with overloads could work (I guess?). Anyway I could work with what it is.

**Comment by anjo76** [comment]
I've fixed the issue with asALREADY_REGISTERED now. 

https://github.com/anjo76/angelscript/commit/8b323e48d1d4b964a4fd43ff122c5146821ca5dc

I've yet to do anything for the function overload matching though, so I'm not closing this issue just yet.
